### ISSUE TITLE
Error by zon

### ISSUE THREAD

**Issue by kapitonoval** [lablabs/cloudflare-exporter#27]
Good Day. 
I have a some problemб when i run docker container without CF_ZONE.
after started command:
docker run --rm -p 8080:8081 -e CF_API_TOKEN=********-e LISTEN=:8081 lablabs/cloudflare_exporter
a had error:
level=error msg="graphql: zone '0aa6db791bbfb2a9cbf5bcc340f78739' does not have access to the path"

Please, help me.

**Comment by martinhaus** [comment]
Hey, are you using free or enterprise plan?

I assume the problem is similar to what was described here https://github.com/lablabs/cloudflare-exporter/issues/5.
The exporter pulls enterprise-level metrics which are not available for zones under a free plan. It would be good if we could disable pulling of these metrics to mitigate this error. 

Feel free to make a contribution if you have time.
